import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { AuthProvider, ReactQueryProvider } from './context'
import { Layout } from '@components/templates'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				style={{ overflow: 'hidden' }}
				className={`${geistSans.variable} ${geistMono.variable}`}
			>
				<ReactQueryProvider>
					<AuthProvider>
						<Layout>{children}</Layout>
					</AuthProvider>
				</ReactQueryProvider>
			</body>
		</html>
	)
}
