import type { Metadata } from 'next'

import { AuthProvider, ReactQueryProvider } from './context'
import { Layout } from '@components/templates'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body style={{ overflow: 'hidden' }}>
				<ReactQueryProvider>
					<AuthProvider>
						<Layout>{children}</Layout>
					</AuthProvider>
				</ReactQueryProvider>
			</body>
		</html>
	)
}
